 language: objective-c
 osx_image: xcode7.3
 install:
   - brew update
   - brew install android-sdk
   - echo y | android update sdk -t android-23 --no-ui
 before_script:
   - export ANDROID_HOME=/usr/local/opt/android-sdk
 script: ./build.sh