env:
  global:
    - DATE=$(date +%Y-%m-%d)
    - PACKAGE_VERSION=$DATE-$TRAVIS_BUILD_NUMBER
language: objective-c
osx_image: xcode8.3
install:
  - brew update
  - brew cask install android-sdk
  - yes | sdkmanager "platforms;android-23"
  - yes | sdkmanager "build-tools;23.0.3"
  - yes | sdkmanager "extras;android;m2repository"
before_script:
  - export ANDROID_HOME=/usr/local/share/android-sdk
script: ./build.sh $PACKAGE_VERSION
